kind: Namespace
apiVersion: v1
metadata:
  name: sink
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
  namespace: sink
  labels:
    app: sink
    type: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sink
  template:
    metadata:
      labels:
        app: sink
    spec:
      containers:
      - name: sink
        image: bryandollery/ndsobc-sink
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sink
  namespace: sink
spec:
  type: ClusterIP
  selector:
    app: sink
  ports:
    - port: 80
      targetPort: 80
---  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sink
  namespace: sink
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /sink(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sink
            port:
              number: 80
